### PR TITLE
deps: update openssl for RUSTSEC-2024-0357

### PR DESCRIPTION
**Pull request by mihirn**

### CODE REVIEW

**Review by thinkingfish — APPROVED** [review]

**Comment by swlynch99** [comment]
Looks like you've got two issues that you need to address:
- You've updated the lockfile into a state where it needs some additional updates. Running `cargo build` and then committing the changes it makes to the lockfile should fix this.
- Due to the update to rust 1.80 it looks like we've also hit https://github.com/rust-lang/rust/issues/125319. You'll need to update the `time` crate to the latest patch release to fix this.

**Comment by mihirn** [comment]
Ugh, thanks. `time` is pulled in from `clocksource` so I'm guessing the better fix is to fix it upstream rather than having an explicit dependency here?

**Comment by swlynch99** [comment]
No it's literally just running `cargo update --precise time`. This is not an issue with clocksource (although clocksource will probably run into a similar issue).

**Comment by mihirn** [comment]
Ok, that worked, thanks!

**Pull request merged**
